name: BestUnitPriceApiClient
targets:
  BestUnitPriceApiClient:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources: [BestUnitPriceApiClient]
    info:
      path: ./Info.plist
      version: v1.0.0
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
    - carthage: Alamofire
