//
// AcceptInvitationCommand.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AcceptInvitationCommand: Codable, JSONEncodable, Hashable {

    public var invitationId: String?
    public var firstName: String?
    public var lastName: String?
    public var phoneNumber: String?
    public var password: String?

    public init(invitationId: String? = nil, firstName: String? = nil, lastName: String? = nil, phoneNumber: String? = nil, password: String? = nil) {
        self.invitationId = invitationId
        self.firstName = firstName
        self.lastName = lastName
        self.phoneNumber = phoneNumber
        self.password = password
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case invitationId
        case firstName
        case lastName
        case phoneNumber
        case password
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(invitationId, forKey: .invitationId)
        try container.encodeIfPresent(firstName, forKey: .firstName)
        try container.encodeIfPresent(lastName, forKey: .lastName)
        try container.encodeIfPresent(phoneNumber, forKey: .phoneNumber)
        try container.encodeIfPresent(password, forKey: .password)
    }
}

