//
// BaseFilter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BaseFilter: Codable, JSONEncodable, Hashable {

    public var advancedSearch: BaseFilterAdvancedSearch?
    public var keyword: String?
    public var advancedFilter: BaseFilterAdvancedFilter?

    public init(advancedSearch: BaseFilterAdvancedSearch? = nil, keyword: String? = nil, advancedFilter: BaseFilterAdvancedFilter? = nil) {
        self.advancedSearch = advancedSearch
        self.keyword = keyword
        self.advancedFilter = advancedFilter
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case advancedSearch
        case keyword
        case advancedFilter
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(advancedSearch, forKey: .advancedSearch)
        try container.encodeIfPresent(keyword, forKey: .keyword)
        try container.encodeIfPresent(advancedFilter, forKey: .advancedFilter)
    }
}

