//
// CreateInvitationCommand.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateInvitationCommand: Codable, JSONEncodable, Hashable {

    static let emailRule = StringRule(minLength: 1, maxLength: 120, pattern: nil)
    static let roleRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var restaurantId: Int64
    public var email: String
    public var role: String
    public var vendor: Int64?

    public init(restaurantId: Int64, email: String, role: String, vendor: Int64? = nil) {
        self.restaurantId = restaurantId
        self.email = email
        self.role = role
        self.vendor = vendor
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case restaurantId
        case email
        case role
        case vendor
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(restaurantId, forKey: .restaurantId)
        try container.encode(email, forKey: .email)
        try container.encode(role, forKey: .role)
        try container.encodeIfPresent(vendor, forKey: .vendor)
    }
}

