//
// ForgotPasswordPost.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class ForgotPasswordPost: Codable, JSONEncodable, Hashable {

    static let passKeyRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let emailRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var passKey: String
    public var email: String

    public init(passKey: String, email: String) {
        self.passKey = passKey
        self.email = email
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case passKey
        case email
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(passKey, forKey: .passKey)
        try container.encode(email, forKey: .email)
    }

    public static func == (lhs: ForgotPasswordPost, rhs: ForgotPasswordPost) -> Bool {
        lhs.passKey == rhs.passKey &&
        lhs.email == rhs.email
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(passKey.hashValue)
        hasher.combine(email.hashValue)
        
    }
}

