//
// MockInventoryItemsPostDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class MockInventoryItemsPostDto: Codable, JSONEncodable, Hashable {

    public var count: Int?

    public init(count: Int? = nil) {
        self.count = count
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case count
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(count, forKey: .count)
    }

    public static func == (lhs: MockInventoryItemsPostDto, rhs: MockInventoryItemsPostDto) -> Bool {
        lhs.count == rhs.count
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(count?.hashValue)
        
    }
}

