//
// PaginationFilter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class PaginationFilter: Codable, JSONEncodable, Hashable {

    public var advancedSearch: BaseFilterAdvancedSearch?
    public var keyword: String?
    public var advancedFilter: BaseFilterAdvancedFilter?
    public var page: Int?
    public var pageSize: Int?
    public var orderBy: [String]?

    public init(advancedSearch: BaseFilterAdvancedSearch? = nil, keyword: String? = nil, advancedFilter: BaseFilterAdvancedFilter? = nil, page: Int? = nil, pageSize: Int? = nil, orderBy: [String]? = nil) {
        self.advancedSearch = advancedSearch
        self.keyword = keyword
        self.advancedFilter = advancedFilter
        self.page = page
        self.pageSize = pageSize
        self.orderBy = orderBy
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case advancedSearch
        case keyword
        case advancedFilter
        case page
        case pageSize
        case orderBy
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(advancedSearch, forKey: .advancedSearch)
        try container.encodeIfPresent(keyword, forKey: .keyword)
        try container.encodeIfPresent(advancedFilter, forKey: .advancedFilter)
        try container.encodeIfPresent(page, forKey: .page)
        try container.encodeIfPresent(pageSize, forKey: .pageSize)
        try container.encodeIfPresent(orderBy, forKey: .orderBy)
    }

    public static func == (lhs: PaginationFilter, rhs: PaginationFilter) -> Bool {
        lhs.advancedSearch == rhs.advancedSearch &&
        lhs.keyword == rhs.keyword &&
        lhs.advancedFilter == rhs.advancedFilter &&
        lhs.page == rhs.page &&
        lhs.pageSize == rhs.pageSize &&
        lhs.orderBy == rhs.orderBy
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(advancedSearch?.hashValue)
        hasher.combine(keyword?.hashValue)
        hasher.combine(advancedFilter?.hashValue)
        hasher.combine(page?.hashValue)
        hasher.combine(pageSize?.hashValue)
        hasher.combine(orderBy?.hashValue)
        
    }
}

