//
// RefreshTokenRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class RefreshTokenRequest: Codable, JSONEncodable, Hashable {

    public var token: String?
    public var refreshToken: String?

    public init(token: String? = nil, refreshToken: String? = nil) {
        self.token = token
        self.refreshToken = refreshToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case token
        case refreshToken
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(token, forKey: .token)
        try container.encodeIfPresent(refreshToken, forKey: .refreshToken)
    }

    public static func == (lhs: RefreshTokenRequest, rhs: RefreshTokenRequest) -> Bool {
        lhs.token == rhs.token &&
        lhs.refreshToken == rhs.refreshToken
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(token?.hashValue)
        hasher.combine(refreshToken?.hashValue)
        
    }
}

