//
// ResetPasswordPost.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class ResetPasswordPost: Codable, JSONEncodable, Hashable {

    static let passKeyRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let emailRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let passwordRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let tokenRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var passKey: String
    public var email: String
    public var password: String
    public var token: String

    public init(passKey: String, email: String, password: String, token: String) {
        self.passKey = passKey
        self.email = email
        self.password = password
        self.token = token
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case passKey
        case email
        case password
        case token
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(passKey, forKey: .passKey)
        try container.encode(email, forKey: .email)
        try container.encode(password, forKey: .password)
        try container.encode(token, forKey: .token)
    }

    public static func == (lhs: ResetPasswordPost, rhs: ResetPasswordPost) -> Bool {
        lhs.passKey == rhs.passKey &&
        lhs.email == rhs.email &&
        lhs.password == rhs.password &&
        lhs.token == rhs.token
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(passKey.hashValue)
        hasher.combine(email.hashValue)
        hasher.combine(password.hashValue)
        hasher.combine(token.hashValue)
        
    }
}

