//
// ResetPasswordRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class ResetPasswordRequest: Codable, JSONEncodable, Hashable {

    public var email: String?
    public var password: String?
    public var token: String?

    public init(email: String? = nil, password: String? = nil, token: String? = nil) {
        self.email = email
        self.password = password
        self.token = token
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case password
        case token
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(password, forKey: .password)
        try container.encodeIfPresent(token, forKey: .token)
    }

    public static func == (lhs: ResetPasswordRequest, rhs: ResetPasswordRequest) -> Bool {
        lhs.email == rhs.email &&
        lhs.password == rhs.password &&
        lhs.token == rhs.token
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(email?.hashValue)
        hasher.combine(password?.hashValue)
        hasher.combine(token?.hashValue)
        
    }
}

