//
// RestaurantPostViewModelAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class RestaurantPostViewModelAllOf: Codable, JSONEncodable, Hashable {

    public var templateRestaurantId: Int64?
    public var template: RestaurantPostViewModelAllOfTemplate?

    public init(templateRestaurantId: Int64? = nil, template: RestaurantPostViewModelAllOfTemplate? = nil) {
        self.templateRestaurantId = templateRestaurantId
        self.template = template
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case templateRestaurantId
        case template
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(templateRestaurantId, forKey: .templateRestaurantId)
        try container.encodeIfPresent(template, forKey: .template)
    }

    public static func == (lhs: RestaurantPostViewModelAllOf, rhs: RestaurantPostViewModelAllOf) -> Bool {
        lhs.templateRestaurantId == rhs.templateRestaurantId &&
        lhs.template == rhs.template
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(templateRestaurantId?.hashValue)
        hasher.combine(template?.hashValue)
        
    }
}

