//
// RestaurantViewModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class RestaurantViewModel: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var addressLine1: String?
    public var addressLine2: String?
    public var city: String?
    public var state: String?
    public var zipCode: String?
    public var geoCached: Bool?
    public var id: Int?

    public init(name: String? = nil, addressLine1: String? = nil, addressLine2: String? = nil, city: String? = nil, state: String? = nil, zipCode: String? = nil, geoCached: Bool? = nil, id: Int? = nil) {
        self.name = name
        self.addressLine1 = addressLine1
        self.addressLine2 = addressLine2
        self.city = city
        self.state = state
        self.zipCode = zipCode
        self.geoCached = geoCached
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case addressLine1
        case addressLine2
        case city
        case state
        case zipCode
        case geoCached
        case id
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(addressLine1, forKey: .addressLine1)
        try container.encodeIfPresent(addressLine2, forKey: .addressLine2)
        try container.encodeIfPresent(city, forKey: .city)
        try container.encodeIfPresent(state, forKey: .state)
        try container.encodeIfPresent(zipCode, forKey: .zipCode)
        try container.encodeIfPresent(geoCached, forKey: .geoCached)
        try container.encodeIfPresent(id, forKey: .id)
    }

    public static func == (lhs: RestaurantViewModel, rhs: RestaurantViewModel) -> Bool {
        lhs.name == rhs.name &&
        lhs.addressLine1 == rhs.addressLine1 &&
        lhs.addressLine2 == rhs.addressLine2 &&
        lhs.city == rhs.city &&
        lhs.state == rhs.state &&
        lhs.zipCode == rhs.zipCode &&
        lhs.geoCached == rhs.geoCached &&
        lhs.id == rhs.id
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name?.hashValue)
        hasher.combine(addressLine1?.hashValue)
        hasher.combine(addressLine2?.hashValue)
        hasher.combine(city?.hashValue)
        hasher.combine(state?.hashValue)
        hasher.combine(zipCode?.hashValue)
        hasher.combine(geoCached?.hashValue)
        hasher.combine(id?.hashValue)
        
    }
}

