//
// RestaurantTemplatePostViewModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RestaurantTemplatePostViewModel: Codable, JSONEncodable, Hashable {

    public var restaurantId: Int64?
    public var includeInventoryItems: Bool?
    public var includeZones: Bool?
    public var includeVendorOverrides: Bool?
    public var includeUnitOverrides: Bool?

    public init(restaurantId: Int64? = nil, includeInventoryItems: Bool? = nil, includeZones: Bool? = nil, includeVendorOverrides: Bool? = nil, includeUnitOverrides: Bool? = nil) {
        self.restaurantId = restaurantId
        self.includeInventoryItems = includeInventoryItems
        self.includeZones = includeZones
        self.includeVendorOverrides = includeVendorOverrides
        self.includeUnitOverrides = includeUnitOverrides
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case restaurantId
        case includeInventoryItems
        case includeZones
        case includeVendorOverrides
        case includeUnitOverrides
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(restaurantId, forKey: .restaurantId)
        try container.encodeIfPresent(includeInventoryItems, forKey: .includeInventoryItems)
        try container.encodeIfPresent(includeZones, forKey: .includeZones)
        try container.encodeIfPresent(includeVendorOverrides, forKey: .includeVendorOverrides)
        try container.encodeIfPresent(includeUnitOverrides, forKey: .includeUnitOverrides)
    }
}

