//
// SeedRestaurantCommand.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class SeedRestaurantCommand: Codable, JSONEncodable, Hashable {

    public var restaurantId: Int64?

    public init(restaurantId: Int64? = nil) {
        self.restaurantId = restaurantId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case restaurantId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(restaurantId, forKey: .restaurantId)
    }

    public static func == (lhs: SeedRestaurantCommand, rhs: SeedRestaurantCommand) -> Bool {
        lhs.restaurantId == rhs.restaurantId
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(restaurantId?.hashValue)
        
    }
}

