//
// ShelvingUnitDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class ShelvingUnitDto: Codable, JSONEncodable, Hashable {

    public var unitNumber: Int?
    public var shelfAmount: Int?
    public var id: Int64?

    public init(unitNumber: Int? = nil, shelfAmount: Int? = nil, id: Int64? = nil) {
        self.unitNumber = unitNumber
        self.shelfAmount = shelfAmount
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case unitNumber
        case shelfAmount
        case id
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(unitNumber, forKey: .unitNumber)
        try container.encodeIfPresent(shelfAmount, forKey: .shelfAmount)
        try container.encodeIfPresent(id, forKey: .id)
    }

    public static func == (lhs: ShelvingUnitDto, rhs: ShelvingUnitDto) -> Bool {
        lhs.unitNumber == rhs.unitNumber &&
        lhs.shelfAmount == rhs.shelfAmount &&
        lhs.id == rhs.id
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(unitNumber?.hashValue)
        hasher.combine(shelfAmount?.hashValue)
        hasher.combine(id?.hashValue)
        
    }
}

