//
// StateViewModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class StateViewModel: Codable, JSONEncodable, Hashable {

    public var id: Int64?
    public var name: String?
    public var abbreviation: String?

    public init(id: Int64? = nil, name: String? = nil, abbreviation: String? = nil) {
        self.id = id
        self.name = name
        self.abbreviation = abbreviation
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case abbreviation
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(abbreviation, forKey: .abbreviation)
    }

    public static func == (lhs: StateViewModel, rhs: StateViewModel) -> Bool {
        lhs.id == rhs.id &&
        lhs.name == rhs.name &&
        lhs.abbreviation == rhs.abbreviation
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id?.hashValue)
        hasher.combine(name?.hashValue)
        hasher.combine(abbreviation?.hashValue)
        
    }
}

