//
// ToggleUserStatusRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class ToggleUserStatusRequest: Codable, JSONEncodable, Hashable {

    public var activateUser: Bool?
    public var userId: String?

    public init(activateUser: Bool? = nil, userId: String? = nil) {
        self.activateUser = activateUser
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case activateUser
        case userId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(activateUser, forKey: .activateUser)
        try container.encodeIfPresent(userId, forKey: .userId)
    }

    public static func == (lhs: ToggleUserStatusRequest, rhs: ToggleUserStatusRequest) -> Bool {
        lhs.activateUser == rhs.activateUser &&
        lhs.userId == rhs.userId
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(activateUser?.hashValue)
        hasher.combine(userId?.hashValue)
        
    }
}

