//
// TokenResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class TokenResponse: Codable, JSONEncodable, Hashable {

    public var token: String?
    public var refreshToken: String?
    public var refreshTokenExpiryTime: Date?

    public init(token: String? = nil, refreshToken: String? = nil, refreshTokenExpiryTime: Date? = nil) {
        self.token = token
        self.refreshToken = refreshToken
        self.refreshTokenExpiryTime = refreshTokenExpiryTime
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case token
        case refreshToken
        case refreshTokenExpiryTime
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(token, forKey: .token)
        try container.encodeIfPresent(refreshToken, forKey: .refreshToken)
        try container.encodeIfPresent(refreshTokenExpiryTime, forKey: .refreshTokenExpiryTime)
    }

    public static func == (lhs: TokenResponse, rhs: TokenResponse) -> Bool {
        lhs.token == rhs.token &&
        lhs.refreshToken == rhs.refreshToken &&
        lhs.refreshTokenExpiryTime == rhs.refreshTokenExpiryTime
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(token?.hashValue)
        hasher.combine(refreshToken?.hashValue)
        hasher.combine(refreshTokenExpiryTime?.hashValue)
        
    }
}

