//
// UpdateRolePermissionsRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class UpdateRolePermissionsRequest: Codable, JSONEncodable, Hashable {

    static let roleIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var roleId: String
    public var permissions: [String]

    public init(roleId: String, permissions: [String]) {
        self.roleId = roleId
        self.permissions = permissions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case roleId
        case permissions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(roleId, forKey: .roleId)
        try container.encode(permissions, forKey: .permissions)
    }

    public static func == (lhs: UpdateRolePermissionsRequest, rhs: UpdateRolePermissionsRequest) -> Bool {
        lhs.roleId == rhs.roleId &&
        lhs.permissions == rhs.permissions
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(roleId.hashValue)
        hasher.combine(permissions.hashValue)
        
    }
}

