//
// UpdateInventoryItemCommand.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateInventoryItemCommand: Codable, JSONEncodable, Hashable {

    public var id: Int64?
    public var name: String?
    public var notes: String?
    public var defaultUnitOfMeasureId: Int64?
    public var defaultQuantity: Double?
    public var defaultCount: Double?
    public var baseQuantity: Int?
    public var currentQuantity: Int?
    public var orderAmount: Int?
    public var ownerId: Int64?
    public var zoneId: Int64?
    public var shelvingUnitId: Int64?
    public var shelfNumber: Int?
    public var active: Bool?

    public init(id: Int64? = nil, name: String? = nil, notes: String? = nil, defaultUnitOfMeasureId: Int64? = nil, defaultQuantity: Double? = nil, defaultCount: Double? = nil, baseQuantity: Int? = nil, currentQuantity: Int? = nil, orderAmount: Int? = nil, ownerId: Int64? = nil, zoneId: Int64? = nil, shelvingUnitId: Int64? = nil, shelfNumber: Int? = nil, active: Bool? = nil) {
        self.id = id
        self.name = name
        self.notes = notes
        self.defaultUnitOfMeasureId = defaultUnitOfMeasureId
        self.defaultQuantity = defaultQuantity
        self.defaultCount = defaultCount
        self.baseQuantity = baseQuantity
        self.currentQuantity = currentQuantity
        self.orderAmount = orderAmount
        self.ownerId = ownerId
        self.zoneId = zoneId
        self.shelvingUnitId = shelvingUnitId
        self.shelfNumber = shelfNumber
        self.active = active
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case notes
        case defaultUnitOfMeasureId
        case defaultQuantity
        case defaultCount
        case baseQuantity
        case currentQuantity
        case orderAmount
        case ownerId
        case zoneId
        case shelvingUnitId
        case shelfNumber
        case active
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(notes, forKey: .notes)
        try container.encodeIfPresent(defaultUnitOfMeasureId, forKey: .defaultUnitOfMeasureId)
        try container.encodeIfPresent(defaultQuantity, forKey: .defaultQuantity)
        try container.encodeIfPresent(defaultCount, forKey: .defaultCount)
        try container.encodeIfPresent(baseQuantity, forKey: .baseQuantity)
        try container.encodeIfPresent(currentQuantity, forKey: .currentQuantity)
        try container.encodeIfPresent(orderAmount, forKey: .orderAmount)
        try container.encodeIfPresent(ownerId, forKey: .ownerId)
        try container.encodeIfPresent(zoneId, forKey: .zoneId)
        try container.encodeIfPresent(shelvingUnitId, forKey: .shelvingUnitId)
        try container.encodeIfPresent(shelfNumber, forKey: .shelfNumber)
        try container.encodeIfPresent(active, forKey: .active)
    }
}

