//
// UpdateUserSettingsCommand.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateUserSettingsCommand: Codable, JSONEncodable, Hashable {

    static let restaurantIdRule = NumericRule<Int>(minimum: nil, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var restaurantId: Int

    public init(restaurantId: Int) {
        self.restaurantId = restaurantId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case restaurantId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(restaurantId, forKey: .restaurantId)
    }
}

