//
// UserRolesRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class UserRolesRequest: Codable, JSONEncodable, Hashable {

    public var userRoles: [UserRoleDto]?

    public init(userRoles: [UserRoleDto]? = nil) {
        self.userRoles = userRoles
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userRoles
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(userRoles, forKey: .userRoles)
    }

    public static func == (lhs: UserRolesRequest, rhs: UserRolesRequest) -> Bool {
        lhs.userRoles == rhs.userRoles
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(userRoles?.hashValue)
        
    }
}

