//
// UserPostViewModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserPostViewModel: Codable, JSONEncodable, Hashable {

    static let emailRule = StringRule(minLength: 0, maxLength: 200, pattern: nil)
    static let passwordRule = StringRule(minLength: 6, maxLength: nil, pattern: nil)
    public var firstName: String?
    public var lastName: String?
    public var email: String
    public var password: String?
    public var roles: [String]?

    public init(firstName: String? = nil, lastName: String? = nil, email: String, password: String? = nil, roles: [String]? = nil) {
        self.firstName = firstName
        self.lastName = lastName
        self.email = email
        self.password = password
        self.roles = roles
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case firstName
        case lastName
        case email
        case password
        case roles
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(firstName, forKey: .firstName)
        try container.encodeIfPresent(lastName, forKey: .lastName)
        try container.encode(email, forKey: .email)
        try container.encodeIfPresent(password, forKey: .password)
        try container.encodeIfPresent(roles, forKey: .roles)
    }
}

