//
// UserRolesRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserRolesRequest: Codable, JSONEncodable, Hashable {

    public var userRoles: [UserRoleDto]?

    public init(userRoles: [UserRoleDto]? = nil) {
        self.userRoles = userRoles
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userRoles
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(userRoles, forKey: .userRoles)
    }
}

