//
// UserViewModelAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class UserViewModelAllOf: Codable, JSONEncodable, Hashable {

    public var isLockedOut: Bool?
    public var accountNumber: String?
    public var monthlyPrice: Double?
    public var roles: [String]?

    public init(isLockedOut: Bool? = nil, accountNumber: String? = nil, monthlyPrice: Double? = nil, roles: [String]? = nil) {
        self.isLockedOut = isLockedOut
        self.accountNumber = accountNumber
        self.monthlyPrice = monthlyPrice
        self.roles = roles
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isLockedOut
        case accountNumber
        case monthlyPrice
        case roles
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(isLockedOut, forKey: .isLockedOut)
        try container.encodeIfPresent(accountNumber, forKey: .accountNumber)
        try container.encodeIfPresent(monthlyPrice, forKey: .monthlyPrice)
        try container.encodeIfPresent(roles, forKey: .roles)
    }

    public static func == (lhs: UserViewModelAllOf, rhs: UserViewModelAllOf) -> Bool {
        lhs.isLockedOut == rhs.isLockedOut &&
        lhs.accountNumber == rhs.accountNumber &&
        lhs.monthlyPrice == rhs.monthlyPrice &&
        lhs.roles == rhs.roles
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(isLockedOut?.hashValue)
        hasher.combine(accountNumber?.hashValue)
        hasher.combine(monthlyPrice?.hashValue)
        hasher.combine(roles?.hashValue)
        
    }
}

