//
// ZoneDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ZoneDto: Codable, JSONEncodable, Hashable {

    public var id: Int64?
    public var name: String?
    public var sortOrder: Int?
    public var shelvingUnits: [ShelvingUnitDto]?

    public init(id: Int64? = nil, name: String? = nil, sortOrder: Int? = nil, shelvingUnits: [ShelvingUnitDto]? = nil) {
        self.id = id
        self.name = name
        self.sortOrder = sortOrder
        self.shelvingUnits = shelvingUnits
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case sortOrder
        case shelvingUnits
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(sortOrder, forKey: .sortOrder)
        try container.encodeIfPresent(shelvingUnits, forKey: .shelvingUnits)
    }
}

