//
// ZoneViewModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class ZoneViewModel: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var sortOrder: Int?
    public var shelvingUnits: [ShelvingUnitViewModel]?
    public var id: Int64?

    public init(name: String? = nil, sortOrder: Int? = nil, shelvingUnits: [ShelvingUnitViewModel]? = nil, id: Int64? = nil) {
        self.name = name
        self.sortOrder = sortOrder
        self.shelvingUnits = shelvingUnits
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case sortOrder
        case shelvingUnits
        case id
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(sortOrder, forKey: .sortOrder)
        try container.encodeIfPresent(shelvingUnits, forKey: .shelvingUnits)
        try container.encodeIfPresent(id, forKey: .id)
    }

    public static func == (lhs: ZoneViewModel, rhs: ZoneViewModel) -> Bool {
        lhs.name == rhs.name &&
        lhs.sortOrder == rhs.sortOrder &&
        lhs.shelvingUnits == rhs.shelvingUnits &&
        lhs.id == rhs.id
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name?.hashValue)
        hasher.combine(sortOrder?.hashValue)
        hasher.combine(shelvingUnits?.hashValue)
        hasher.combine(id?.hashValue)
        
    }
}

