//
// AddOrderItemViewModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AddOrderItemViewModel: Codable, JSONEncodable, Hashable {

    public var inventoryItemId: Int64?
    public var quantity: Int?
    public var inventory: Int?

    public init(inventoryItemId: Int64? = nil, quantity: Int? = nil, inventory: Int? = nil) {
        self.inventoryItemId = inventoryItemId
        self.quantity = quantity
        self.inventory = inventory
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case inventoryItemId
        case quantity
        case inventory
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(inventoryItemId, forKey: .inventoryItemId)
        try container.encodeIfPresent(quantity, forKey: .quantity)
        try container.encodeIfPresent(inventory, forKey: .inventory)
    }
}

