//
// CreateRestaurantCommand.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateRestaurantCommand: Codable, JSONEncodable, Hashable {

    static let nameRule = StringRule(minLength: 1, maxLength: 255, pattern: nil)
    static let addressLine1Rule = StringRule(minLength: 1, maxLength: 255, pattern: nil)
    static let zipCodeRule = StringRule(minLength: 1, maxLength: 5, pattern: nil)
    public var name: String
    public var addressLine1: String
    public var addressLine2: String?
    public var city: String?
    public var state: String?
    public var zipCode: String
    public var restaurantId: Int64?
    public var includeInventoryItems: Bool?
    public var includeZones: Bool?
    public var includeVendorOverrides: Bool?
    public var includeUnitOverrides: Bool?

    public init(name: String, addressLine1: String, addressLine2: String? = nil, city: String? = nil, state: String? = nil, zipCode: String, restaurantId: Int64? = nil, includeInventoryItems: Bool? = nil, includeZones: Bool? = nil, includeVendorOverrides: Bool? = nil, includeUnitOverrides: Bool? = nil) {
        self.name = name
        self.addressLine1 = addressLine1
        self.addressLine2 = addressLine2
        self.city = city
        self.state = state
        self.zipCode = zipCode
        self.restaurantId = restaurantId
        self.includeInventoryItems = includeInventoryItems
        self.includeZones = includeZones
        self.includeVendorOverrides = includeVendorOverrides
        self.includeUnitOverrides = includeUnitOverrides
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case addressLine1
        case addressLine2
        case city
        case state
        case zipCode
        case restaurantId
        case includeInventoryItems
        case includeZones
        case includeVendorOverrides
        case includeUnitOverrides
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(addressLine1, forKey: .addressLine1)
        try container.encodeIfPresent(addressLine2, forKey: .addressLine2)
        try container.encodeIfPresent(city, forKey: .city)
        try container.encodeIfPresent(state, forKey: .state)
        try container.encode(zipCode, forKey: .zipCode)
        try container.encodeIfPresent(restaurantId, forKey: .restaurantId)
        try container.encodeIfPresent(includeInventoryItems, forKey: .includeInventoryItems)
        try container.encodeIfPresent(includeZones, forKey: .includeZones)
        try container.encodeIfPresent(includeVendorOverrides, forKey: .includeVendorOverrides)
        try container.encodeIfPresent(includeUnitOverrides, forKey: .includeUnitOverrides)
    }
}

