//
// OrderPutViewModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OrderPutViewModel: Codable, JSONEncodable, Hashable {

    public var id: Int64?
    @available(*, deprecated, message: "This property is deprecated.")
    public var createdDate: Date?
    public var totalPrice: Float?
    public var active: Bool?
    public var status: OrderStatus?
    public var invoice: String?
    public var deliveryDate: Date?
    public var orderDate: Date?
    public var number: String?

    public init(id: Int64? = nil, createdDate: Date? = nil, totalPrice: Float? = nil, active: Bool? = nil, status: OrderStatus? = nil, invoice: String? = nil, deliveryDate: Date? = nil, orderDate: Date? = nil, number: String? = nil) {
        self.id = id
        self.createdDate = createdDate
        self.totalPrice = totalPrice
        self.active = active
        self.status = status
        self.invoice = invoice
        self.deliveryDate = deliveryDate
        self.orderDate = orderDate
        self.number = number
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case createdDate
        case totalPrice
        case active
        case status
        case invoice
        case deliveryDate
        case orderDate
        case number
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(createdDate, forKey: .createdDate)
        try container.encodeIfPresent(totalPrice, forKey: .totalPrice)
        try container.encodeIfPresent(active, forKey: .active)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(invoice, forKey: .invoice)
        try container.encodeIfPresent(deliveryDate, forKey: .deliveryDate)
        try container.encodeIfPresent(orderDate, forKey: .orderDate)
        try container.encodeIfPresent(number, forKey: .number)
    }
}

