//
// OrderStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public enum OrderStatus: Int, Codable, CaseIterable {
    case _1 = 1
    case _2 = 2
    case _3 = 3
}
