//
// ResetPasswordPostAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ResetPasswordPostAllOf: Codable, JSONEncodable, Hashable {

    static let emailRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let passwordRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let tokenRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var email: String
    public var password: String
    public var token: String

    public init(email: String, password: String, token: String) {
        self.email = email
        self.password = password
        self.token = token
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case password
        case token
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encode(password, forKey: .password)
        try container.encode(token, forKey: .token)
    }
}

