//
// UserRoleDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserRoleDto: Codable, JSONEncodable, Hashable {

    public var roleId: String?
    public var roleName: String?
    public var description: String?
    public var enabled: Bool?

    public init(roleId: String? = nil, roleName: String? = nil, description: String? = nil, enabled: Bool? = nil) {
        self.roleId = roleId
        self.roleName = roleName
        self.description = description
        self.enabled = enabled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case roleId
        case roleName
        case description
        case enabled
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(roleId, forKey: .roleId)
        try container.encodeIfPresent(roleName, forKey: .roleName)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(enabled, forKey: .enabled)
    }
}

